UPDATE SUBMISSION SET SubDate = CURRENT_TIMESTAMP - INTERVAL FLOOR(RAND() * 14) DAY;

UPDATE SUBMISSION SET SubDeadline = '2017-12-01';

ALTER TABLE SUBMISSION ADD Bonus int(11);

UPDATE SUBMISSION SET Bonus = 10;

UPDATE SUBMISSION SET SubGrade = 10 WHERE SubDeadline > SubDate;

UPDATE COURSE_GRADE SET Midterm = FLOOR(0 + RAND() * 100);

UPDATE COURSE_GRADE SET Final = FLOOR(0 + RAND() * 100);

UPDATE COURSE_GRADE SET Lab = FLOOR(0 + RAND() * 100);

ALTER TABLE COURSE_GRADE ADD Quiz int(11);

UPDATE COURSE_GRADE SET Quiz = FLOOR(0 + RAND() * 100);

ALTER TABLE COURSE_GRADE ADD Overall int(11);

UPDATE COURSE_GRADE inner join STUDENT on COURSE_GRADE.StudentID=STUDENT.StudentID set COURSE_GRADE.Overall=floor(((COURSE_GRADE.Midterm*25)+(COURSE_GRADE.Quiz*15)+(COURSE_GRADE.Lab*20)+(COURSE_GRADE.Final*40))/100);

